// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq2fW_0eu--YzWbCWnU0Ki54zZGkvRnxY',
    appId: '1:849323926155:web:d675ed68c6fc858ab32a8e',
    messagingSenderId: '849323926155',
    projectId: 'currensee-backend-ce094',
    authDomain: 'currensee-backend-ce094.firebaseapp.com',
    storageBucket: 'currensee-backend-ce094.firebasestorage.app',
    measurementId: 'G-CBS5K1JTWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaqsnC-qJ8yOecvKUqv21B7ufISflcqkw',
    appId: '1:849323926155:android:f5c28316615f14d8b32a8e',
    messagingSenderId: '849323926155',
    projectId: 'currensee-backend-ce094',
    storageBucket: 'currensee-backend-ce094.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQfRJFYGu9t1dTtjmkh0ViopGeWRWlcFc',
    appId: '1:849323926155:ios:e4bda9f923b191e9b32a8e',
    messagingSenderId: '849323926155',
    projectId: 'currensee-backend-ce094',
    storageBucket: 'currensee-backend-ce094.firebasestorage.app',
    iosClientId: '849323926155-08aoj17d7r5vr2go8ab2e2044pjg7tsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQfRJFYGu9t1dTtjmkh0ViopGeWRWlcFc',
    appId: '1:849323926155:ios:e4bda9f923b191e9b32a8e',
    messagingSenderId: '849323926155',
    projectId: 'currensee-backend-ce094',
    storageBucket: 'currensee-backend-ce094.firebasestorage.app',
    iosClientId: '849323926155-08aoj17d7r5vr2go8ab2e2044pjg7tsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq2fW_0eu--YzWbCWnU0Ki54zZGkvRnxY',
    appId: '1:849323926155:web:489b186268b51aaab32a8e',
    messagingSenderId: '849323926155',
    projectId: 'currensee-backend-ce094',
    authDomain: 'currensee-backend-ce094.firebaseapp.com',
    storageBucket: 'currensee-backend-ce094.firebasestorage.app',
    measurementId: 'G-GCY6CQ1LC8',
  );
}
